### PR TITLE
migrate faac facts page to narepng

### PR DESCRIPTION
**Pull request by OdunayoOkebunmi**
added landing page

### CODE REVIEW

**Comment by frknasir** [comment]
@OdunayoOkebunmi Could you resolve the conflict please? Its hard to review it with so many changes from other PRs.

**Comment by frknasir** [comment]
@OdunayoOkebunmi The tableu embedding is not loading from my end...was it working on yours?

**Comment by OdunayoOkebunmi** [comment]
> @OdunayoOkebunmi The tableau embedding is not loading from my end...was it working on yours?

Screenshot 2020-08-03 at 16 25 02

**Comment by frknasir** [comment]
> > @OdunayoOkebunmi The tableau embedding is not loading from my end...was it working on yours?
> > Yes, it is
> 
> Screenshot 2020-08-03 at 16 25 02

okay

**Comment by frknasir** [comment]
@OdunayoOkebunmi you have some duplicate named routes 

`[vue-router] Duplicate named routes definition: { name: "faac-facts", path: "/faac-facts/13-percent-derivation" }`
`[vue-router] Duplicate named routes definition: { name: "faac-facts", path: "/faac-facts/13-percent-derivation/2007" }`
`[vue-router] Duplicate named routes definition: { name: "faac-facts", path: "/faac-facts/13-percent-derivation/2008" }`

you could edit the names to `faac-facts-2007`, `faac-facts-2008`...etc

**Comment by frknasir** [comment]
> @OdunayoOkebunmi The tableu embedding is not loading from my end...was it working on yours?

@OdunayoOkebunmi So i had a mixed content error because i was loading a secured iframe(http://public.tableau.com/views/2007FAACDisbursement/Dashboard1?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Fpublic.tableau.com%2F&:embed_code_version=3&:tabs=no&:toolbar=yes&:animate_transition=yes&:display_static_image=no&:display_spinner=no&:display_overlay=yes&:display_count=yes&publish=yes&:loadOrderID=0&:size=1110,1&&:showVizHome=n&:bootstrapWhenNotified=y&:tabs=n&:apiID=host0#navType=1&navSrc=Parse) over a secured page(https://narepng.test)

Could you update the link to a `https`?

**Comment by frknasir** [comment]
@OdunayoOkebunmi right now, when you go from one year to the other, the table is not automatically updated. To achieve that, you can add `data` and `watch` options in `TableuHolder` component as in the following:

```javascript
data() {
    return {
      viz: null
    }
  },
  watch: {
    url: function (val) {
      this.viz = null
      this.initViz()
    }
  },
```

and `mounted` option as in the following:

```javascript
mounted () {
    this.initViz()
  }
```

**Comment by frknasir** [comment]
@OdunayoOkebunmi Also, the progress loader is not finishing properly as you go from route to route. What can be done here is to import `NProgress`(import NProgress from "nprogress) in each of the components and implement a `mounted` option as in the following:

```javascript
mounted() {
    NProgress.done()
  }
```

**Comment by frknasir** [comment]
@OdunayoOkebunmi And, lastly, conflicts are still not resolved

**Pull request merged**
