### PR TITLE
Update Spoorng Landing Page

### PR DESCRIPTION
**Pull request by OdunayoOkebunmi**
Link to issue #4

### CODE REVIEW

**Comment by frknasir** [comment]
Screenshot 2020-07-19 at 00 07 47

This is what im seeing testing this PR...are you still working on it? There are conflicts here too

**Comment by OdunayoOkebunmi** [comment]
> Screenshot 2020-07-19 at 00 07 47
> 
> This is what im seeing testing this PR...are you still working on it? There are conflicts here too

No, all work has been completed

**Comment by frknasir** [comment]
Okay...next step is to just run things by the project manager(bassim) to make sure we are all on the same table...or have you done that?

**Comment by OdunayoOkebunmi** [comment]
> Okay...next step is to just run things by the project manager(bassim) to make sure we are all on the same table...or have you done that?

Yes, I have. @AMG63-Bassim is fine with the current implementation

**Comment by frknasir** [comment]
> > Okay...next step is to just run things by the project manager(bassim) to make sure we are all on the same table...or have you done that?
> 
> Yes, I have. @AMG63-Bassim is fine with the current implementation

alright great...ill give it one more look then merge. thanks!

**Pull request merged**
